### ISSUE TITLE
BUG: survey generated gives a blank page, probably because surveyjs.azureedge.net is no longer available

### ISSUE THREAD

**Issue by hugolytics** [cguardia/questions#230]
* Questions version: stable
* Python version: 3.10.3
* Operating System: mac os catalina

### Description

My survey is not showing up.
Even if I run the simple flask app demo code from the documentation, when I run the app and open the web address, there is a blank page.
When I inspect the page, I can see the surveyjs elements. However the page is blank.

<img width="1743" alt="image" src="https://user-images.githubusercontent.com/93601551/180315296-1816a6bf-26c5-4e6e-bb21-f4dca2cb5da1.png">

### What I Did
 there are no errors in the code are the flask app

I disabled all extensions, turned off any protection/blocking feature and tried multiple web browsers and multiple development environments.
But the problem persists.

any idea on whats going on?

The same code worked two months ago.

**Comment by hugolytics** [comment]
the HTML generated for the example flask app from the questions documentation yields:
`

  | <!DOCTYPE html>
-- | --
  | <html lang="en">
  | <head>
  | <title>Profile</title>
  | <meta name="viewport" content="width=device-width"/>
  | <script src="https://unpkg.com/jquery@3.5.1/dist/jquery.js"></script>
  | <script src="https://surveyjs.azureedge.net/1.8.2/survey.jquery.min.js"></script>
  | <script src="https://unpkg.com/inputmask@5.0.3/dist/inputmask.js"></script>
  | <script src="https://surveyjs.azureedge.net/1.8.2/surveyjs-widgets.js"></script>
  | <link href="https://surveyjs.azureedge.net/1.8.2/survey.css" type="text/css" rel="stylesheet" />
  |  
  | </head>
  | <body>
  |  
  | <div id="questions_form" style="display:inline-block;width:100%;"></div>
  |  
  | <script type="text/javascript">
  | Survey
  | .StylesManager
  | .applyTheme('default');
  |  
  | var json = {"title": "", "pages": [{"name": "default", "title": "", "questions": [], "maxTimeToFinish": 0, "navigationButtonsVisibility": "inherit", "questionTitleLocation": "default", "questionsOrder": "default"}, {"name": "PageOne", "title": "Identification Information", "questions": [{"type": "text", "name": "name", "title": "", "description": "", "isRequired": false, "visible": true, "defaultValue": "", "correctAnswer": "", "visibleIf": "", "enableIf": "", "startWithNewLine": true, "valueName": "", "requiredIf": "", "requiredErrorText": "", "hideNumber": true, "indent": 0, "titleLocation": "default", "descriptionLocation": "default", "width": "", "maxWidth": "initial", "minWidth": "300px", "useDisplayValuesInTitle": true, "validators": [], "placeHolder": "", "inputType": "text", "maxLength": -1, "max": "", "min": "", "size": 0, "step": "", "textUpdateMode": "default", "inputMask": "", "inputFormat": "", "prefix": "", "autoUnmask": true}, {"type": "text", "name": "email", "title": "", "description": "", "isRequired": "True", "visible": true, "defaultValue": "", "correctAnswer": "", "visibleIf": "", "enableIf": "", "startWithNewLine": true, "valueName": "", "requiredIf": "", "requiredErrorText": "", "hideNumber": true, "indent": 0, "titleLocation": "default", "descriptionLocation": "default", "width": "", "maxWidth": "initial", "minWidth": "300px", "useDisplayValuesInTitle": true, "validators": [], "placeHolder": "", "inputType": "email", "maxLength": -1, "max": "", "min": "", "size": 0, "step": "", "textUpdateMode": "default", "inputMask": "", "inputFormat": "", "prefix": "", "autoUnmask": true}], "maxTimeToFinish": 0, "navigationButtonsVisibility": "inherit", "questionTitleLocation": "default", "questionsOrder": "default"}, {"name": "PageTwo", "title": "Additional Information", "questions": [{"type": "dropdown", "name": "country", "title": "", "description": "", "isRequired": false, "visible": true, "defaultValue": "", "correctAnswer": "", "visibleIf": "", "enableIf": "", "startWithNewLine": true, "valueName": "", "requiredIf": "", "requiredErrorText": "", "hideNumber": true, "indent": 0, "titleLocation": "default", "descriptionLocation": "default", "width": "", "maxWidth": "initial", "minWidth": "300px", "useDisplayValuesInTitle": true, "validators": [], "colCount": 4, "choices": [], "choicesByUrl": {"value_name": "name", "url": "https://restcountries.eu/rest/v2/all"}, "choicesOrder": "none", "choicesEnableIf": "", "choicesVisibleIf": "", "hideIfChoicesEmpty": true, "hasOther": false, "otherText": "Other", "otherErrorText": "", "otherPlaceHolder": "", "choicesMax": 0, "choicesMin": 0, "choicesStep": 1, "optionsCaption": "", "showOptionsCaption": true}, {"type": "text", "name": "birthdate", "title": "", "description": "", "isRequired": false, "visible": true, "defaultValue": "", "correctAnswer": "", "visibleIf": "", "enableIf": "", "startWithNewLine": true, "valueName": "", "requiredIf": "", "requiredErrorText": "", "hideNumber": true, "indent": 0, "titleLocation": "default", "descriptionLocation": "default", "width": "", "maxWidth": "initial", "minWidth": "300px", "useDisplayValuesInTitle": true, "validators": [], "placeHolder": "", "inputType": "date", "maxLength": -1, "max": "", "min": "", "size": 0, "step": "", "textUpdateMode": "default", "inputMask": "", "inputFormat": "", "prefix": "", "autoUnmask": true}], "maxTimeToFinish": 0, "navigationButtonsVisibility": "inherit", "questionTitleLocation": "default", "questionsOrder": "default"}], "calculatedValues": [], "checkErrorsMode": "onNextPage", "clearInvisibleValues": "onComplete", "completedBeforeHtml": "", "completedHtml": "", "completedHtmlOnCondition": [], "completeText": "", "cookieName": "", "description": "", "editText": "", "firstPageIsStarted": false, "focusFirstQuestionAutomatic": true, "focusOnFirstError": true, "goNextPageAutomatic": false, "loadingHtml": "", "locale": "", "logo": "", "logoFit": "contain", "logoHeight": 200, "logoPosition": "left", "logoWidth": 300, "maxOthersLength": 0, "maxTextLength": 0, "maxTimeToFinish": 0, "mode": "edit", "navigateToUrl": "", "navigateToUrlOnCondition": [], "pageNextText": "", "pagePrevText": "", "previewText": "", "progressBarType": "pages", "questionDescriptionLocation": "underTitle", "questionErrorLocation": "top", "questionsOnPageMode": "standard", "questionsOrder": "initial", "questionStartIndex": "", "questionTitleLocation": "top", "questionTitlePattern": "numTitleRequire", "questionTitleTemplate": "", "requiredText": "*", "sendResultOnPageNext": false, "showCompletedPage": false, "showNavigationButtons": "bottom", "showPageNumbers": true, "showPageTitles": true, "showPrevButton": true, "showPreviewBeforeComplete": "noPreview", "showProgressBar": "off", "showQuestionNumbers": "on", "showTimerPanel": "none", "showTimerPanelMode": "all", "showTitle": true, "startSurveyText": "", "storeOthersAsComment": true, "surveyId": "", "surveyPostId": "", "surveyShowDataSaving": true, "textUpdateMode": "onBlur", "triggers": []};
  |  
  | var data = {};
  |  
  | var sendDataToServer = function(sender, options) {
  |  
  | var errorMessage = "Something went wrong on the server side. Please try again."
  |  
  | if (sender.isLastPage) {
  |  
  | fetch('', {
  | method: 'post',
  | headers: {
  | 'Accept': 'text/html, text/plain, */*',
  | 'Content-Type': 'application/json'
  | },
  | body: JSON.stringify(sender.data)
  | })
  | .then(function(response) {
  | replace_html = false;
  | if (response.ok) {
  | if (response.redirected) {
  | sender.navigateToUrl=response.url;
  | } else {
  | replace_html = response.text().then(function(text) {
  | document.open();
  | document.write(text);
  | setTimeout(function() {
  | var pages = survey.visiblePages;
  | var error_page = -1;
  | for (var i=0; i<pages.length; i++){
  | if (pages[i].hasErrors(true, true)) {
  | error_page = i;
  | break;
  | }
  | }
  | if (error_page != -1) {
  | survey.currentPageNo = error_page;
  | }
  | }, 500);
  | });
  | }
  | } else {
  | first = sender.getAllQuestions()[0];
  | options.errors[first] = response.statusText + ": " + errorMessage;
  | }
  | return replace_html;
  | })
  | .then(function(result) {
  | if (!result) {
  | options.complete();
  | }
  | })
  | .catch (function(error) {
  | first_question = sender.getAllQuestions()[0];
  | options.errors[first_question.name] = error.message + ": " + errorMessage;
  | options.complete();
  | });
  |  
  | } else {
  | options.complete();
  |  
  | }
  | }
  |  
  | var survey = new Survey.Model(json);
  | survey.data = data;
  | survey.onServerValidateQuestions.add(sendDataToServer);
  | $("#questions_form").Survey({
  | model:survey,
  | });
  | </script>
  |  
  | </body>
  | </html>

`

**Comment by hugolytics** [comment]
And if you try to open https://surveyjs.azureedge.net/1.8.2/survey.jquery.min.js
you get:

This site can’t be reached
Check if there is a typo in surveyjs.azureedge.net.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by hugolytics** [comment]
so maybe instead one should use:
https://unpkg.com/survey-jquery@1.8.2/survey.jquery.js

probably the azureedge cdns should be deprecated

**Comment by hugolytics** [comment]
source: https://www.cdnpkg.com/survey-jquery
according to https://github.com/surveyjs/builds

**Comment by hugolytics** [comment]
running:
`download_surveyjs ./src/app/static react bootstrap`

gives the following error:
```
Downloaded ./src/app/static/polyfill.js
Downloaded ./src/app/static/react.js
Downloaded ./src/app/static/react-dom.js
Downloaded ./src/app/static/babel.min.js
Traceback (most recent call last):
  File "./.venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/./venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/hugoevers/.pyenv/versions/3.10.3/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "./.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "./.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "./.venv/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "./.venv/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x10e62ee30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./.venv/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "./.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "./.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='surveyjs.azureedge.net', port=443): Max retries exceeded with url: /1.8.2/survey.react.min.js (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10e62ee30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
....
  File "./.venv/lib/python3.10/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='surveyjs.azureedge.net', port=443): Max retries exceeded with url: /1.8.2/survey.react.min.js (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10e62ee30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
(.venv) hugoevers@MBP-van-Hugo CA_data_platform % download_surveyjs ./src/app/static jquery bootstrap

Downloaded ./src/app/static/jquery.js
Traceback (most recent call last):
  File "./venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "./.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/hugoevers/.pyenv/versions/3.10.3/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "./.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "./.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "./.venv/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "./.venv/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x106693250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./.venv/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "./.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "./.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='surveyjs.azureedge.net', port=443): Max retries exceeded with url: /1.8.2/survey.jquery.min.js (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106693250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./.venv/bin/download_surveyjs", line 8, in <module>
    sys.exit(download_surveyjs())
...
    r = adapter.send(request, **kwargs)
  File "./venv/lib/python3.10/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='surveyjs.azureedge.net', port=443): Max retries exceeded with url: /1.8.2/survey.jquery.min.js (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106693250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

**Comment by cguardia** [comment]
Sorry this took so long to fix. Thanks a lot for the detailed description.
