### ISSUE TITLE
Change language of the forms

### ISSUE THREAD

**Issue by yassinebha** [cguardia/questions#253]
* Questions version: Latest version
* Python version: 3.9
* Operating System: conda in windows 10

Hi Carlos, I love the tool you developed. I'm wondering how can I change the language of the forms let say from English to French?

Thanks a lot

**Comment by cguardia** [comment]
Sure, you can set the locale when instantiating the form, like this:

`form = YourFormSubclass(title="Formulaire en français", locale="fr")`

**Comment by cguardia** [comment]
Added this to the docs, so closing.
