### ISSUE TITLE
Default value in question

### ISSUE THREAD

**Issue by yassinebha** [cguardia/questions#267]
* Questions version: Latest
* Python version:
* Operating System: windows 10 pro

### Description

Hi! I use Question to administer a questionnairse with most of the questions are not required or mendatory. So if some one doesn't respond to a couple of questions, I end up with no variables name for these questions in my csv dataframe. 

I'm wondering is there a way to have default values il all the questions? 

Thanks Carlos

**Comment by cguardia** [comment]
Sure, you can pass in a `default_value` when instantiating the question, like this:

`name = TextQuestion(default_value="John Smith")`

**Comment by yassinebha** [comment]
Excellent! Thanks Carlos!
