### ISSUE TITLE
Switching between themes has lost its relevance

### ISSUE THREAD

**Issue by rilshok** [cguardia/questions#360]
The [official SurveyJS website says](https://surveyjs.io/form-library/documentation/manage-default-themes-and-styles) that some of the names for the themes are out of date. These themes are defined in `questions.settings.SURVEY_JS_THEMES`, but `questions.templates.get_theme_css_resources` function does not support them. Since these themes are obsolete, it would probably be wise to disable their support altogether. What is really missing, however, is support for the modern DefaultV2 theme. At the moment I was able to implement its support, with a very simple stub:

```python3
from questions import Form

class FormDefaultV2(Form):
    @property
    def required_css(self):
        return ["https://unpkg.com/survey-core/defaultV2.min.css"]
 ```
 
 The survey form looks and works great.

**Comment by cguardia** [comment]
Thanks a lot for letting me know about this. Updated code and docs to use current themes and default to V2.
