### ISSUE TITLE
ReadMe example broken 

### ISSUE THREAD

**Issue by Irtazaraza** [cguardia/questions#438]
* Questions version: latest
* Python version: 3.9
* Operating System: MAC OS

### Description

The example in the read me and the docs does not work any more. When i try to run it. The web page just says: `The survey doesn't contain visible pages or questions.`

**Comment by Irtazaraza** [comment]
@cguardia Any update on the above please?

**Comment by Irtazaraza** [comment]
Apparently the format of the JSON produced is invalid: https://surveyjs.io/form-library/documentation/troubleshooting

**Comment by cguardia** [comment]
@Irtazaraza Questions is not yet compatible with pydantic V2. Pushed a fix to main.
