### ISSUE TITLE
Panels seem to be broken

### ISSUE THREAD

**Issue by Irtazaraza** [cguardia/questions#439]
* Questions version: latest
* Python version: 3.8
* Operating System: mac OS

### Description

When i try the panels example from the docs i get the following error thrown when the `.render_html()` function is called on the final `ProfileForm` class object: `{AttributeError}'Survey' object has no attribute 'questions'`

**Comment by cguardia** [comment]
@Irtazaraza Thanks for the report. Pushed a fix for this to main branch.
